python run.py \
    --model_name_or_path="/models/bloomz-1b1" \
    --quantization_bit 4 \
    --dataset_path="./dataset/train/exp/train.jsonl" \
    --report_to="none" \
    --finetuning_type="lora" \
    --learning_rate=1.41e-5 \
    --per_device_train_batch_size=1 \
    --per_device_eval_batch_size=1 \
    --eval_strategy "epoch" \
    --gradient_accumulation_steps=1 \
    --output_dir="sft_openassistant-guanaco" \
    --overwrite_output_dir \
    --logging_steps=1 \
    --num_train_epochs=3 \
    --max_samples=100 \
    --max_steps=-1 \
    --val_size=.1 \
    --gradient_checkpointing \
    --bf16 \
    --do_train 